version: '3.8'
services:
  api:
    build: ./api
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=postgres://postgres:pass@db:5432/anime
      - MONGO_URL=mongodb://mongo:27017/anime
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=anime
    depends_on: ["db","mongo","redis","minio"]
    volumes:
      - ./storage:/work/storage

  worker:
    build: ./worker
    depends_on: ["redis","minio"]
    volumes:
      - ./storage:/work/storage

  transcoder:
    build: ./transcoder
    volumes:
      - ./storage:/work/storage

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: anime
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:
